### ISSUE TITLE
Not working on Python 3.6

### ISSUE THREAD

**Issue by pathcl** [PyCQA/pep8#447]
pathcl@sid:~/src/osquery$ find . -name '*.py' | xargs pep8
Traceback (most recent call last):
  File "/home/pathcl/.pyenv/versions/3.6-dev/bin/pep8", line 7, in <module>
    from pep8 import _main
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pep8.py", line 1343, in <module>
    init_checks_registry()
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pep8.py", line 1342, in init_checks_registry
    register_check(function)
  File "/home/pathcl/.pyenv/versions/3.6-dev/lib/python3.6/site-packages/pep8.py", line 1325, in register_check
    args = inspect.getargspec(check)[0]
AttributeError: module 'inspect' has no attribute 'getargspec'

pathcl@sid:~/src/osquery$ python -V
Python 3.6.0a0

**Comment by pathcl** [comment]
'getargsspec' is deprecated onwards 3.6 https://docs.python.org/3.6/whatsnew/3.6.html#removed

**Comment by sigmavirus24** [comment]
This is fixed in master by https://github.com/PyCQA/pep8/pull/420

**Comment by jayvdb** [comment]
Any chance of a release soonish?  This is breaking any Python nightly build which uses the packaged pep8
e.g. https://travis-ci.org/jayvdb/nested-dict/jobs/89913570#L163

**Comment by sigmavirus24** [comment]
Nightly Python builds are Python 3.6, i.e., they're inherently not supported by the packaged version. For nightly versions, you should try master. We will not be creating releases for every bug that Python 3.6 introduces in the 1.5 years until it is released.
